name: Deploy Hugo site to ECS

on:
  push:
    branches:
      - master
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "Deploy"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 检出代码，包括submodules，保证主题文件正常
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      # 准备Hugo环境
      - name: Hugo setup
        uses: peaceiris/actions-hugo@v2
        hugo-version: '0.121.2'
        extended: true
      # Hugo构建静态站点，默认输出到public目录下
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: hugo --minify
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public
      # 将public目录下的所有内容同步到远程服务器的nginx站点路径，注意path参数的写法，'public'和'public/'是不同的
      - name: rsync deployments
        uses: burnett01/rsync-deployments@7.0.0
        with:
          switches: -avzr --delete
          path: ./public/
          # 需要先手动在远程主机创建该目录，否则会执行失败
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          # ssh 私钥
          remote_key: ${{ secrets.DEPLOY_KEY }}
    